# Generated by Django 5.1.2 on 2025-10-18 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="attachment",
            new_name="files_attac_type_58af65_idx",
            old_name="files_attac_type_b2e44c_idx",
        ),
        migrations.RenameIndex(
            model_name="attachment",
            new_name="files_attac_sha256_087402_idx",
            old_name="files_attac_sha256_ef7458_idx",
        ),
    ]
