# Generated by Django 5.1.2 on 2025-11-01 16:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mpn', models.CharField(help_text="Manufacturer's part number", max_length=255, verbose_name='Manufacturer Part Number')),
                ('mpn_norm', models.CharField(blank=True, db_index=True, help_text='Normalized MPN for consistent lookups', max_length=255, null=True, verbose_name='Normalized MPN')),
                ('manufacturer', models.CharField(max_length=255)),
                ('manufacturer_norm', models.CharField(blank=True, db_index=True, help_text='Normalized manufacturer name for consistent lookups', max_length=255, null=True, verbose_name='Normalized Manufacturer')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('tolerance', models.CharField(blank=True, max_length=50, null=True)),
                ('wattage', models.CharField(blank=True, max_length=50, null=True)),
                ('voltage', models.CharField(blank=True, max_length=50, null=True)),
                ('current', models.CharField(blank=True, max_length=50, null=True)),
                ('package_name', models.CharField(blank=True, max_length=100, null=True)),
                ('package_l_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Package Length (mm)')),
                ('package_w_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Package Width (mm)')),
                ('package_h_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Package Height (mm)')),
                ('pins', models.IntegerField(blank=True, null=True)),
                ('pitch_mm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='Pin Pitch (mm)')),
                ('description', models.TextField(blank=True, null=True)),
                ('lifecycle', models.CharField(choices=[('ACTIVE', 'Active'), ('NRND', 'Not Recommended for New Designs'), ('EOL', 'End of Life'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('rohs', models.BooleanField(blank=True, null=True)),
                ('temp_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('url_datasheet', models.URLField(blank=True, null=True)),
                ('url_alt', models.URLField(blank=True, null=True)),
                ('category_l1', models.CharField(default='Unsorted', help_text='Primary category', max_length=100)),
                ('category_l2', models.CharField(blank=True, help_text='Secondary category', max_length=100, null=True)),
                ('dmtuid', models.CharField(blank=True, help_text='Full DMT code (e.g., DMT-02030110001)', max_length=20, null=True, unique=True)),
                ('dmt_tt', models.CharField(blank=True, help_text='Domain code (00-99)', max_length=2, null=True)),
                ('dmt_ff', models.CharField(blank=True, help_text='Family code (00-99)', max_length=2, null=True)),
                ('dmt_cc', models.CharField(blank=True, help_text='Class code (00-99)', max_length=2, null=True)),
                ('dmt_ss', models.CharField(blank=True, help_text='Style code (00-99)', max_length=2, null=True)),
                ('dmt_xxx', models.CharField(blank=True, help_text='Sequence number (001-999)', max_length=3, null=True)),
                ('footprint_name', models.CharField(blank=True, max_length=255, null=True)),
                ('step_model_path', models.CharField(blank=True, max_length=255, null=True)),
                ('extras', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'indexes': [models.Index(fields=['mpn'], name='inventory_c_mpn_f5a50e_idx'), models.Index(fields=['manufacturer'], name='inventory_c_manufac_000ad5_idx'), models.Index(fields=['category_l1'], name='inventory_c_categor_604702_idx'), models.Index(fields=['dmtuid'], name='inventory_c_dmtuid_630782_idx'), models.Index(fields=['dmt_tt', 'dmt_ff', 'dmt_cc', 'dmt_ss'], name='inventory_c_dmt_tt_cce4a4_idx')],
                'unique_together': {('manufacturer_norm', 'mpn_norm')},
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('uom', models.CharField(choices=[('pcs', 'Pieces'), ('reel', 'Reel'), ('tube', 'Tube'), ('tray', 'Tray')], default='pcs', max_length=10, verbose_name='Unit of Measure')),
                ('storage_location', models.CharField(max_length=255)),
                ('lot_code', models.CharField(blank=True, max_length=100, null=True)),
                ('date_code', models.CharField(blank=True, max_length=100, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('price_each', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('condition', models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('expired', 'Expired')], default='new', max_length=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='inventory.component')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
            },
        ),
    ]
