# Generated by Django 5.1.2 on 2025-10-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="component",
            new_name="inventory_c_mpn_f5a50e_idx",
            old_name="inventory_co_mpn_554202_idx",
        ),
        migrations.RenameIndex(
            model_name="component",
            new_name="inventory_c_manufac_000ad5_idx",
            old_name="inventory_co_manufac_b5b18e_idx",
        ),
        migrations.RenameIndex(
            model_name="component",
            new_name="inventory_c_categor_604702_idx",
            old_name="inventory_co_categor_b0c6f7_idx",
        ),
        migrations.AlterUniqueTogether(
            name="component",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="component",
            name="manufacturer_norm",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized manufacturer name for consistent lookups",
                max_length=255,
                null=True,
                verbose_name="Normalized Manufacturer",
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="mpn_norm",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Normalized MPN for consistent lookups",
                max_length=255,
                null=True,
                verbose_name="Normalized MPN",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="component",
            unique_together={("manufacturer_norm", "mpn_norm")},
        ),
    ]
