# Generated by Django 5.1.2 on 2025-10-18 16:07

import re
from django.db import migrations


def normalize_string(value):
    """Normalize a string by removing extra spaces and converting to uppercase"""
    if not value:
        return value
    # Replace Unicode dashes with ASCII hyphen
    value = re.sub(r'[\u2010-\u2015]', '-', value)
    # Remove extra spaces and convert to uppercase
    return re.sub(r'\s+', ' ', value).strip().upper()


def populate_normalized_fields(apps, schema_editor):
    """Populate normalized fields for existing components"""
    Component = apps.get_model('inventory', 'Component')
    for component in Component.objects.all():
        component.mpn_norm = normalize_string(component.mpn)
        component.manufacturer_norm = normalize_string(component.manufacturer)
        component.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0002_rename_inventory_co_mpn_554202_idx_inventory_c_mpn_f5a50e_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(populate_normalized_fields, migrations.RunPython.noop),
    ]
